# Generated by Django 3.2.25 on 2025-05-14 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='cree_par',
        ),
        migrations.AlterField(
            model_name='chambre',
            name='statut',
            field=models.CharField(choices=[('Libre', 'Libre'), ('Occupée', 'Occupée')], default='Libre', max_length=20),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='statut',
            field=models.CharField(max_length=50),
        ),
    ]
