# Generated by Django 3.2.25 on 2025-05-16 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservations', '0002_auto_20250514_1756'),
    ]

    operations = [
        migrations.AddField(
            model_name='chambre',
            name='prix',
            field=models.DecimalField(decimal_places=2, default=200000, max_digits=10),
            preserve_default=False,
        ),
    ]
